version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - migrate
  devtools:
    build:
      context: .
      dockerfile: docker/devtools/Dockerfile
    volumes:
      - .:/usr/src/app
  migrate:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    command: ['python', 'manage.py', 'migrate']
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
