# Generated by Django 2.2.6 on 2019-10-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=200)),
                ('platform_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Commment',
            new_name='Comment',
        ),
        migrations.AddField(
            model_name='thread',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threads.Entity'),
        ),
    ]
