# Generated by Django 2.2.7 on 2019-11-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0001_squashed_0005_auto_20191112_1305"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
