# Generated by Django 2.2.6 on 2019-10-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20191022_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='platform_id',
            new_name='provider_id',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='platform_id',
            new_name='provider_id',
        ),
    ]
