# Generated by Django 2.2.9 on 2020-01-23 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0002_autor_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                ("created_at", models.DateTimeField()),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=200)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="threads.Comment",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="threads.Thread"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="threads.User"
                    ),
                ),
            ],
        ),
    ]
