apiVersion: v1
kind: Service
metadata:
  name: {{ template "comments.fullname" . }}
  labels:
    {{ include "comments.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "comments.name" . }}
    release: {{ .Release.Name }}